sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: sky_take_out
    username: root
    password: Hiiragi0406.
  redis:
    host: localhost
    port: 6379
    password: Hiiragi0406.
    database: 0
  wechat:
    appid: wx8ab3101865c9b418
    secret: 42426c983e8e2fdbfbf4ed3c77ef0689
